03_module: first module implementation
Kernel-GL-HRK/gl-kernel-training-2021 pull request #35
Opened 2021-02-23 16:33 UTC by ASynenko

Simple kernel module implemention.

2021-02-24 23:39 UTC, ReAlUA requested changes

2021-02-24 23:39 UTC, ReAlUA commented on 03_module/first_module.c
> +	return 0;
Implement task point 4.

2021-02-24 23:58 UTC, ReAlUA commented
You can also add
```c
MODULE_PARM_DESC(user_name, "User name");
MODULE_PARM_DESC(ansver, "User answer to the Ultimate Question");
```
for better `modinfo first_module.ko` output

2021-02-25 00:00 UTC, ReAlUA commented on 03_module/first_module.c
> +module_param(ansver, int, 0);
*answer*

2021-02-25 10:59 UTC, ASynenko commented on 03_module/first_module.c
> +module_param(ansver, int, 0);
fixed

2021-02-25 10:59 UTC, ASynenko commented on 03_module/first_module.c
> +	return 0;
Done

2021-02-25 12:30 UTC, ReAlUA approved these changes
See comment.
You may merge this PR.

2021-02-25 12:30 UTC, ReAlUA commented on 03_module/Makefile
> +KDIR = ~/Projects/repos/linux/kernel/linux-stable/
Removing of `?` may help when troubleshooting bot now
```bash
export TARGET=BBB
export KDIR=~/GL-LKT/repos/linux-stable/
make
```
does not work. Only this way is possible:
```bash
export TARGET=BBB
make KDIR=~/GL-LKT/repos/linux-stable/
```
It's not a big deal for this homework but read more about env / command line assignments priorities in makefiles.

2021-02-25 13:43 UTC, merged