03module
Kernel-GL-HRK/gl-kernel-training-2021 pull request #38
Opened 2021-02-24 18:05 UTC by denanko

Implementation of kernel module, which purpose is to fail randomly during insertion (insmod).

2021-02-24 21:58 UTC, alexposukhov requested changes

2021-02-24 21:58 UTC, alexposukhov commented on 03_module/trouble_module.c
> +	get_random_bytes(&rand_number, 1);
Please remove this line.
task 4 is related to module parameter. and output  dependent on this parameter.
In this case you are able to transfer this parameter into module as "insmod trouble_module.ko rand_number=60" or "insmod trouble_module.ko rand_number=20"

2021-02-25 07:11 UTC, denanko commented
Done. But I would like to save this line as commented out.

2021-02-25 08:11 UTC, denanko commented
Done

2021-02-25 08:43 UTC, alexposukhov approved these changes

2021-02-25 08:43 UTC, merged