Module homework
Kernel-GL-HRK/gl-kernel-training-2021 pull request #41
Opened 2021-02-26 06:43 UTC by virkha

Add simple module

2021-03-03 06:33 UTC, virkha commented
Add all action items in module

2021-03-03 06:45 UTC, ekovalyov requested changes
Please check coding style with checkpatch.pl

2021-03-04 19:38 UTC, virkha commented
Fix coding style issue

2021-03-08 08:51 UTC, ekovalyov approved these changes

2021-03-08 08:51 UTC, merged