Task_06: Timers
Kernel-GL-HRK/gl-kernel-training-2021 pull request #76
Opened 2021-03-07 10:20 UTC by denanko

Module which works with timers using sysfs

2021-03-09 08:32 UTC, alexposukhov requested changes

2021-03-09 08:32 UTC, alexposukhov commented on 06_timers/userspace_script/show_time.c
> +	printf("Absolute time is %ld.%ld seconds.\n", now.tv_sec, now.tv_nsec);
Please convert this time to Human readable format.

2021-03-10 07:01 UTC, denanko commented
show_time.c was updated with requested changes.

2021-03-10 07:53 UTC, alexposukhov requested changes

2021-03-10 07:53 UTC, alexposukhov commented on 06_timers/userspace_script/show_time.c
> +			hrt->tm_mon, hrt->tm_mday);
According to struct tm specification:
int tm_mon;         /* month, range 0 to 11             */
So in this case printf shows wrong month

2021-03-10 07:54 UTC, alexposukhov commented on 06_timers/userspace_script/show_time.c
> +			hrt->tm_mon, hrt->tm_mday);
Please add day of week

2021-03-10 07:58 UTC, denanko commented
Month format fixed.

2021-03-10 08:01 UTC, alexposukhov approved these changes

2021-03-10 08:01 UTC, merged