07_memory: solution implementation
Kernel-GL-HRK/gl-kernel-training-2021 pull request #89
Opened 2021-03-10 11:01 UTC by ASynenko

Kmodule tests memory allocation with different functions and prints out statistics. 
Uspace routine with same functional.

2021-03-12 16:36 UTC, ReAlUA requested changes

2021-03-12 16:36 UTC, ReAlUA commented on 07_memory/kmodule/memory_module.c
> +	ktime_delta >>= 4;
There is unclear connection between `4` and `MEMTEST_ATEMPTS`.
Use something like
```
#define MEMTEST_ATTEMPTS_POWER 4
#define MEMTEST_ATTEMPTS (1 << MEMTEST_ATTEMPTS_POWER)
```

2021-03-12 16:36 UTC, ReAlUA commented on 07_memory/kmodule/memory_module.c
> +		for (funk_indx = MEMTS_KMALLOC;
Unclear. "Does `MEMTS_KMALLOC` equal zero?", etc.
This enum is not necessary at all because it is used _only_ for array creation and loop limit.
Use
```c
struct mem_ops memtest_func[] = {
	{"KMALLOC", &my_kmalloc, &my_kfree},
	...
};	

for (index = 0; index < ARRAY_SIZE(memtest_func); index++)
```
And take a look on the ARRAY_SIZE macro.

2021-03-12 16:36 UTC, ReAlUA commented on 07_memory/kmodule/memory_module.c
> +	buffer = test_func->space_alloc(1);
`cache`

2021-03-12 16:36 UTC, ReAlUA commented on 07_memory/kmodule/memory_module.c
> +}
Indentation

2021-03-14 12:52 UTC, ASynenko commented on 07_memory/kmodule/memory_module.c
> +	ktime_delta >>= 4;
Fixed

2021-03-14 12:52 UTC, ASynenko commented on 07_memory/kmodule/memory_module.c
> +	buffer = test_func->space_alloc(1);
Fixed

2021-03-14 12:52 UTC, ASynenko commented on 07_memory/kmodule/memory_module.c
> +}
Fixed

2021-03-14 12:54 UTC, ASynenko commented on 07_memory/kmodule/memory_module.c
> +		for (funk_indx = MEMTS_KMALLOC;
Fixed. Removed unnecessary enum. Initialy was used for single function tests.

2021-03-14 16:55 UTC, ReAlUA requested changes

2021-03-14 16:55 UTC, ReAlUA commented on 07_memory/uspace/main.c
> +	while (res == 0) {
Endless loop.
`alloca`: "If the allocation causes stack overflow, program behavior is undefined."
On my BBB, it always returns non-zero and `res = memtest()` overrides `res` from preceding allocators.

2021-03-15 08:08 UTC, ASynenko commented on 07_memory/uspace/main.c
> +	while (res == 0) {
Fixed.

2021-03-15 17:28 UTC, ReAlUA requested changes

2021-03-15 17:28 UTC, ReAlUA commented on 07_memory/uspace/main.c
> +	while (res == 0) {
In the module, but not in the uspace.

2021-03-17 20:39 UTC, ReAlUA approved these changes

2021-03-17 20:40 UTC, merged